language: php

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
          env: SYMFONY_VERSION=4.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.4
          env: SYMFONY_VERSION=5.1.*
        - php: nightly
          env: COMPOSER_FLAGS="--ignore-platform-reqs"

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER="max[total]=999"
        - COMPOSER_FLAGS="--prefer-dist"

before_script:
    - composer self-update
    - |
      if [ "$SYMFONY_VERSION" != "" ]; then
           sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
      fi;
    - if [ "$COMPOSER_FLAGS" == "--prefer-lowest" ]; then composer require --dev "doctrine/lexer:v1.0.1" --no-update; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
