name: build

on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    phpstan:
        runs-on: ubuntu-24.04
        name: PHPStan
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              env:
                  REQUIRE_DEV: true
              with:
                  args: analyse
    cs-fixer:
        runs-on: ubuntu-24.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run
    tests:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - description: 'Lowest'
                      php: '8.2'
                      symfony: 6.4.*
                      dependencies: lowest
                    - description: 'Symfony 7.4'
                      php: '8.4'
                      symfony: 7.4.*
                    - description: 'Symfony 8.0'
                      php: '8.5'
                      symfony: 8.0.*
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
            - name: Allow dev dependencies
              run: composer config minimum-stability dev && composer config prefer-stable true
              if: contains(matrix.symfony, '@dev')
            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
            - name: Run tests
              run: bin/phpunit --colors=always --coverage-clover=clover.xml
            - name: save test coverage
              if: ${{ matrix.php == '8.4' }}
              uses: qltysh/qlty-action/coverage@v1
              with:
                  token: ${{secrets.QLTY_COVERAGE_TOKEN}}
                  files: clover.xml
